### ISSUE TITLE
Crash with BeEF

### ISSUE THREAD

**Issue by thezakman** [byt3bl33d3r/MITMf#106] opened 2015-06-02 02:53 UTC
Any Idea why this?
```
beefapi ERROR: No JSON object could be decoded: line 1 column 0 (char 0)
Exception in thread BeEFAutorun-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/easylife/MITMf/plugins/BeefAutorun.py", line 60, in startThread
    self.autorun()
  File "/root/easylife/MITMf/plugins/BeefAutorun.py", line 80, in autorun
    self.execModules(session)
  File "/root/easylife/MITMf/plugins/BeefAutorun.py", line 103, in execModules
    if resp["success"] == 'true':
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by thezakman** [comment] 2015-06-02 02:56
Exception happened during processing of request from ('192.168.0.9', 7708)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/root/easylife/MITMf/core/dnschef/DNSchef.py", line 376, in handle
    response = self.parse(data)
  File "/root/easylife/MITMf/core/dnschef/DNSchef.py", line 107, in parse
    response = self.hstsbypass(qname[3:], qname, nameservers, d)
  File "/root/easylife/MITMf/core/dnschef/DNSchef.py", line 359, in hstsbypass
    dns_rr = DNSRecord.parse(r).rr
  File "/usr/local/lib/python2.7/dist-packages/dnslib/dns.py", line 96, in parse
    buffer = DNSBuffer(packet)
  File "/usr/local/lib/python2.7/dist-packages/dnslib/label.py", line 204, in __init__
    super(DNSBuffer,self).__init__(data)
  File "/usr/local/lib/python2.7/dist-packages/dnslib/buffer.py", line 49, in __init__
    self.data = bytearray(data)
TypeError: 'NoneType' object is not iterable

**Comment by byt3bl33d3r** [comment] 2015-06-02 13:27
@thezakman hi, 
Can you give me the full command string you used and the OS your running?
Thanks

**Comment by byt3bl33d3r** [comment] 2015-06-02 13:35
@thezakman also if you can paste the Beefautorun section in the config file that would be awesome

**Comment by thezakman** [comment] 2015-06-02 16:07
Sure, I'm not at home now but once I am I will post.

Enviada do meu iPad

**Comment by byt3bl33d3r** [comment] 2015-06-03 22:30
@thezakman any update?

**Comment by thezakman** [comment] 2015-06-04 00:59
Yes, here is another error with the same command.

mitmf -i wlan0 --jskeylogger --hsts --ferretng --screen --spoof --arp --target 192.168.1.107 --gateway 192.168.1.1 --beefauto

after 30 lines working i got this.

2015-06-03 21:58:04 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:07 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:10 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:13 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:16 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:19 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:22 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:25 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:28 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:31 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:34 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:38 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:41 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:44 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:47 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:50 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')
2015-06-03 21:58:53 [ARPpoisoner] Exception occurred while poisoning 192.168.1.107: (4, 'Interrupted system call')

**Comment by thezakman** [comment] 2015-06-04 01:00
Linux darkmatter 3.18.0-kali3-686-pae #1 SMP Debian 3.18.6-1~kali2 (2015-03-02) i686 GNU/Linux

**Comment by thezakman** [comment] 2015-06-04 01:03
Settings and files are all default, except for the lock.ico that i updated.

**Comment by byt3bl33d3r** [comment] 2015-06-05 01:55
@thezakman the ```'Interrupted system call'``` is related to #109, It doesn't affect the Arp spoofing or other functionality in any way. 

I'm still unable to reproduce this, can you paste the output of ```pip freeze```, this is most likely a dependency issue

**Comment by auraltension** [comment] 2015-06-06 07:15
I'm gonna put this here as it's related to BeEFAutorun also.

    $ sudo python mitmf.py -i eth1 --beefauto --spoof --arp --arpmode req --gateway 172.16.0.1 --targets 192.16.0.251

```
2015-06-06 17:10:07 192.16.0.251 [BeEFAutorun] Injected malicious html: thrillhousearcade.com
2015-06-06 17:10:07 192.16.0.251 [type:AndroidBrowser os:Android /1.0 (ancora IMM76L)] Sending Request: www.google
.com.au
2015-06-06 17:10:08 192.16.0.251 [BeEFAutorun] Injected malicious html: www.google.com.au
2015-06-06 17:10:09 192.16.0.251 >> joined the horde! [id:1, type:None-UNKNOWN, os:None]
2015-06-06 17:10:09 192.16.0.251 >> sending generic modules
2015-06-06 17:10:09 192.16.0.251 >> sent module 82
2015-06-06 17:10:10 192.16.0.251 >> sending targeted modules
Exception in thread BeEFAutorun-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/dev/clone/MITMf/plugins/BeefAutorun.py", line 60, in startThread
    self.autorun()
  File "/home/user/dev/clone/MITMf/plugins/BeefAutorun.py", line 84, in autorun
    self.execModules(session)
  File "/home/user/dev/clone/MITMf/plugins/BeefAutorun.py", line 111, in execModules
    if (os in hook_os) or (os == hook_os):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by byt3bl33d3r** [comment] 2015-06-06 11:10
@auraltension ahhhh! thanks! the error makes a lot more sense now, I'll push a fix later today!

**Comment by byt3bl33d3r** [comment] 2015-06-06 12:32
@auraltension @thezakman if you guys could confirm this too that would be great! 

thanks everybody! :)

**Comment by thezakman** [comment] 2015-06-06 17:45
Will update here and check in a few, thanks @byt3bl33d3r

**Comment by auraltension** [comment] 2015-06-07 06:36
I haven't seen it while running at all, but upon termination of the program I now see errors  relating to beef.

```
2015-06-07 16:11:02 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.150
2015-06-07 16:11:11 [ARPpoisoner] Unable to resolve MAC address of 192.16.0.150
^C

beefapi ERROR: 'NoneType' object is not callable
```
and another

```
2015-06-07 16:25:59 192.16.0.150 >> sending generic modules
2015-06-07 16:26:00 192.16.0.150 >> sent module 82
2015-06-07 16:27:31 192.16.0.150 [type:Chrome 43.0.2357.80 os:MacOS Macintosh X 10.10.1] Sending Request: ping.chartbeat.net
^[[Cbeefapi ERROR: 'NoneType' object is not callable
Exception in thread BeEFAutorun-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/dev/clone/MITMf/plugins/BeefAutorun.py", line 60, in startThread
    self.autorun()
  File "/home/user/dev/clone/MITMf/plugins/BeefAutorun.py", line 88, in autorun
    sleep(1)
TypeError: 'NoneType' object is not callable

$ 
```

**Comment by auraltension** [comment] 2015-06-07 06:37
Which is also meaning that I am often not seeing any re-arping messages.

**Comment by byt3bl33d3r** [comment] 2015-06-08 02:22
@auraltension @thezakman I basically re-wrote the whole API from scratch lol, let me know if you still get the above error

**Comment by byt3bl33d3r** [comment] 2015-06-10 00:58
Closing since I'm pretty sure it's resolved

**Closed** 2015-06-10 00:58 UTC
Labels: bug, unable to reproduce
