### ISSUE TITLE
Just dunno bug

### ISSUE THREAD

**Issue by twixst** [byt3bl33d3r/MITMf#189] opened 2015-09-07 15:05 UTC
Hi, ive installed mitmf according to the guide, but i dont get any output besides MITMf logo
Ubuntu 14.04 64bit 

pip freeze output 

```
beautifulsoup4==4.4.0
capstone==3.0.4
cffi==1.2.1
characteristic==14.3.0
chardet==2.3.0
configobj==5.0.6
cryptography==1.0.1
dnslib==0.9.4
dnspython==1.12.0
enum34==1.0.4
Flask==0.10.1
idna==2.0
ipaddress==1.0.14
IPy==0.83
itsdangerous==0.24
Jinja2==2.8
lxml==3.4.4
MarkupSafe==0.23
msgpack-python==0.4.6
netaddr==0.7.18
NetfilterQueue==0.6
pefile==1.2.10.post114
Pillow==2.9.0
pyasn1==0.1.8
pyasn1-modules==0.0.7
pycparser==2.14
pycrypto==2.6.1
pyinotify==0.9.6
pyOpenSSL==0.15.1
pypcap==1.1.3
python-magic==0.4.6
PyYAML==3.11
requests==2.7.0
scapy==2.3.1
service-identity==14.0.0
six==1.9.0
Twisted==15.4.0
ua-parser==0.4.1
user-agents==1.0.1
Werkzeug==0.10.4
wheel==0.24.0
zope.interface==4.1.2
```

```
(MITMf)bdtm@o:~/MITMf$ ./mitmf.py -help

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒ 
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░ 
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░ 
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░    
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░    
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░      
░      ░    ▒ ░  ░      ░      ░    ░ ░    
       ░    ░                  ░                                                     

[-] The derp is strong with this one
(MITMf)bdtm@o:~/MITMf$
```
```
(MITMf)bdtm@o:~/MITMf$ ./mitmf.py --log debug
                                                    
 __  __   ___   .--.          __  __   ___              
|  |/  `.'   `. |__|         |  |/  `.'   `.      _.._  
|   .-.  .-.   '.--.     .|  |   .-.  .-.   '   .' .._| 
|  |  |  |  |  ||  |   .' |_ |  |  |  |  |  |   | '     
|  |  |  |  |  ||  | .'     ||  |  |  |  |  | __| |__   
|  |  |  |  |  ||  |'--.  .-'|  |  |  |  |  ||__   __|  
|  |  |  |  |  ||  |   |  |  |  |  |  |  |  |   | |     
|__|  |__|  |__||__|   |  |  |__|  |__|  |__|   | |     
                       |  '.'                   | |     
                       |   /                    | |     
                       `'-'                     |_|

[-] The derp is strong with this one
(MITMf)bdtm@o:~/MITMf$
```

**Comment by HAMIDx9** [comment] 2015-09-07 15:09
Hi, 
MITMf requires root privilege to run properly.
this is not a bug.
Please close this issue.

**Closed** 2015-09-07 15:12 UTC

**Comment by JeromSar** [comment] 2016-05-24 16:02
Honestly, this could have been documented better. "The derp is strong with this one is." is a really confusing (and mocking) message.
