### ISSUE TITLE
inject and jskeylogger cant handle websites with umlaute (äöü)

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#143] opened 2015-08-02 13:41 UTC
please fix that because any inject causes cryptic signs on the place of umlaut (äöü)
thanks!

p.s. and the keylogger fails with errors if anyone types a umlaut in a textfield

**Comment by byt3bl33d3r** [comment] 2015-08-02 15:44
@WiredLife hi, 
this is a duplicate of #56 and isn't a priority at the moment, if this is something important to you feel free to submit a pull request :) 

thanks

**Closed by byt3bl33d3r** 2015-08-02 15:44 UTC
Labels: duplicate
