### ISSUE TITLE
SMB Error

### ISSUE THREAD

**Issue by DrDinosaur** [byt3bl33d3r/MITMf#120] opened 2015-06-10 08:48 UTC
```
root@Kali:~/Scripts/MITMf# ./mitmf.py -i eth0 --spoof --arp --filepwn --targets 192.168.2.50 --gateway 192.168.2.1

███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

[*] MITMf v0.9.7 online... initializing plugins
|_ FilePwn v0.3
|  |_ BDFProxy v0.3.2 online
|  |_ Connected to Metasploit v4.11.2-2015052901
|_ Spoof v0.6
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "./mitmf.py", line 186, in <module>
    from core.servers.smb.SMBserver import SMBserver
  File "/root/Scripts/MITMf/core/servers/smb/SMBserver.py", line 8, in <module>
    from core.servers.smb.KarmaSMB import KarmaSMBServer
  File "/root/Scripts/MITMf/core/servers/smb/KarmaSMB.py", line 65, in <module>
    from impacket.smbserver import SRVSServer, decodeSMBString, findFirst2, STATUS_SMB_BAD_TID, encodeSMBString, \
ImportError: cannot import name STATUS_SMB_BAD_TID
```
Latest copy.

**Comment by byt3bl33d3r** [comment] 2015-06-10 09:34
This is a duplicate of #116, Upgrade your impacket version and it will work just fine

**Closed by byt3bl33d3r** 2015-06-10 09:34 UTC

**Comment by DrDinosaur** [comment] 2015-06-10 09:54
Yep, works now.

**Comment by vapor99** [comment] 2015-06-11 03:20
Updating doesn't work for me.  :(

------------

root@kali:~/scripts/MITMf# pip install --upgrade -r requirements.txt
Requirement already up-to-date: Twisted in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: netaddr in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: scapy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: msgpack-python in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: dnslib in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: configobj in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already up-to-date: pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already up-to-date: ipy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already up-to-date: pyopenssl in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already up-to-date: service-identity in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already up-to-date: watchdog in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already up-to-date: impacket in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14))
Requirement already up-to-date: capstone in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15))
Requirement already up-to-date: pypcap in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16))
Requirement already up-to-date: zope.interface>=3.6.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1))
Requirement already up-to-date: six in /usr/local/lib/python2.7/dist-packages (from configobj->-r requirements.txt (line 7))
Requirement already up-to-date: cryptography>=0.7 in /usr/local/lib/python2.7/dist-packages (from pyopenssl->-r requirements.txt (line 11))
Requirement already up-to-date: characteristic>=14.0.0 in /usr/local/lib/python2.7/dist-packages (from service-identity->-r requirements.txt (line 12))
Requirement already up-to-date: pyasn1 in /usr/local/lib/python2.7/dist-packages (from service-identity->-r requirements.txt (line 12))
Requirement already up-to-date: pyasn1-modules in /usr/local/lib/python2.7/dist-packages (from service-identity->-r requirements.txt (line 12))
Requirement already up-to-date: PyYAML>=3.10 in /usr/local/lib/python2.7/dist-packages (from watchdog->-r requirements.txt (line 13))
Requirement already up-to-date: argh>=0.24.1 in /usr/local/lib/python2.7/dist-packages (from watchdog->-r requirements.txt (line 13))
Requirement already up-to-date: pathtools>=0.1.1 in /usr/local/lib/python2.7/dist-packages (from watchdog->-r requirements.txt (line 13))
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=3.6.0->Twisted->-r requirements.txt (line 1))
Requirement already up-to-date: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 11))
Requirement already up-to-date: idna in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 11))
Requirement already up-to-date: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 11))
Requirement already up-to-date: cffi>=0.8 in /usr/local/lib/python2.7/dist-packages (from cryptography>=0.7->pyopenssl->-r requirements.txt (line 11))
Requirement already up-to-date: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=0.8->cryptography>=0.7->pyopenssl->-r requirements.txt (line 11))

root@kali:~/scripts/MITMf# ./mitmf.py -i wlan0

 ███▄ ▄███▓ ██▓▄▄▄█████▓ ███▄ ▄███▓  █████▒
▓██▒▀█▀ ██▒▓██▒▓  ██▒ ▓▒▓██▒▀█▀ ██▒▓██   ▒
▓██    ▓██░▒██▒▒ ▓██░ ▒░▓██    ▓██░▒████ ░
▒██    ▒██ ░██░░ ▓██▓ ░ ▒██    ▒██ ░▓█▒  ░
▒██▒   ░██▒░██░  ▒██▒ ░ ▒██▒   ░██▒░▒█░
░ ▒░   ░  ░░▓    ▒ ░░   ░ ▒░   ░  ░ ▒ ░
░  ░      ░ ▒ ░    ░    ░  ░      ░ ░
░      ░    ▒ ░  ░      ░      ░    ░ ░
       ░    ░                  ░

[*] MITMf v0.9.7 online... initializing plugins
|
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|_ Net-Creds v1.0 online
|_ DNSChef v0.4 online
Traceback (most recent call last):
  File "./mitmf.py", line 186, in <module>
    from core.servers.smb.SMBserver import SMBserver
  File "/root/scripts/MITMf/core/servers/smb/SMBserver.py", line 8, in <module>
    from core.servers.smb.KarmaSMB import KarmaSMBServer
  File "/root/scripts/MITMf/core/servers/smb/KarmaSMB.py", line 65, in <module>
    from impacket.smbserver import SRVSServer, decodeSMBString, findFirst2, STATUS_SMB_BAD_TID, encodeSMBString, \
ImportError: cannot import name STATUS_SMB_BAD_TID

**Comment by DrDinosaur** [comment] 2015-06-11 03:26
Get their repo and run the setup script.

**Comment by vapor99** [comment] 2015-06-11 03:30
Yep, that did it!  Thanks!
