### ISSUE TITLE
Write capture file

### ISSUE THREAD

**Issue by AresS31** [byt3bl33d3r/MITMf#306] opened 2016-04-22 00:11 UTC
Hi,
Maybe you should think about giving users the possibility to save logs weherever they want (and not only in the big messy mitmf.log). Also I think it could be awesome to be able to log the sniffing session as .pcap and .cap file to be able to open them with any other advanced sniffing tools such as tcpdump/wireshark... or better to be able to directly use net cred on them.
You are doing an awesome job, mitmf is for me the best MITM framework so far.
Keep on doing the good work.
Best,
Alexandre

**Comment by byt3bl33d3r** [comment] 2016-06-03 20:45
Duplicate of #220

**Closed by byt3bl33d3r** 2016-06-03 20:45 UTC
Labels: duplicate
