### ISSUE TITLE
JSkeylogger does not return data input field on certain sites

### ISSUE THREAD

**Issue by WiredLife** [byt3bl33d3r/MITMf#147] opened 2015-08-04 14:16 UTC
```
2015-08-04 01:12:59 192.168.175.3 [type:Chrome Mobile-43 os:Android] www.otto.de
2015-08-04 01:12:59 [ProxyPlugins] Exception occurred in hooked function
Traceback (most recent call last):
  File "/root/MITMf/core/sergioproxy/ProxyPlugins.py", line 112, in hook
    a = f(**args)
  File "/root/MITMf/plugins/jskeylogger.py", line 39, in request
    input_field = request.postData.split("&&")[1]
IndexError: list index out of range
```

**Comment by byt3bl33d3r** [comment] 2015-08-05 11:39
@WiredLife will look into this tmw, thanks!

**Comment by HAMIDx9** [comment] 2015-08-25 10:21
@WiredLife , @byt3bl33d3r, I couldn't reproduce the bug, is there any specific site to debug?
Thanks

**Comment by byt3bl33d3r** [comment] 2015-08-25 13:23
@HAMIDx9 I failed to reproduce this to... @WiredLife what website did you go to?

**Comment by byt3bl33d3r** [comment] 2015-08-25 14:58
Also, for future reference, please see https://github.com/byt3bl33d3r/MITMf/wiki/Reporting-a-bug on how to report a bug

**Comment by byt3bl33d3r** [comment] 2015-08-27 01:23
Closing since I'm unable to reproduce this in anyway

**Closed by byt3bl33d3r** 2015-08-27 01:23 UTC
Labels: bug, plugin, unable to reproduce
