### ISSUE TITLE
Have you finished beefauto plugin yet?

### ISSUE THREAD

**Issue by anonymous4ever1** [byt3bl33d3r/MITMf#320] opened 2016-06-22 08:59 UTC
As you said in #179 you were going to finish that plugin and I haven't seen any other answer about it, I wonder whether there's any way of connecting MITMf with BeEF.

Thanks.

**Comment by byt3bl33d3r** [comment] 2016-12-13 04:23
I think so, although I cannot seem to find the code lol. If I find it I'll push it up.
Duplicate of #328

**Closed by byt3bl33d3r** 2016-12-13 04:23 UTC
