### ISSUE TITLE
Arp Spoofing does nothing

### ISSUE THREAD

**Issue by MrabEzreb** [byt3bl33d3r/MITMf#324] opened 2016-07-06 02:46 UTC
P.S. Wireshark is showing that arp packets are being sent
P.P.S Wireshark seems to be saying that it is setting the target IP and the gateway IP to my mac address, is something wierd going on with the --targets option?

My command is: python mitmf.py --log-level debug -i wlan0 --spoof --arp --dns --gateway 10.26.0.4 --target 10.26.184.201 --replace
(the target is my phone, with mobile data turned off so it must use wifi)
I installed everything exactly as the installation guide says to.
It gets to the bottom and it sits there forever, no matter what sites I go to on my phone.
Any help?
Log:

``````
███╗   ███╗██╗████████╗███╗   ███╗███████╗
████╗ ████║██║╚══██╔══╝████╗ ████║██╔════╝
██╔████╔██║██║   ██║   ██╔████╔██║█████╗  
██║╚██╔╝██║██║   ██║   ██║╚██╔╝██║██╔══╝  
██║ ╚═╝ ██║██║   ██║   ██║ ╚═╝ ██║██║     
╚═╝     ╚═╝╚═╝   ╚═╝   ╚═╝     ╚═╝╚═╝     

2016-07-05 19:42:52 MITMf started: ['mitmf.py', '--log-level', 'debug', '-i', 'wlan0', '--spoof', '--arp', '--dns', '--gateway', '10.26.0.4', '--target', '10.26.184.201', '--replace']
[*] MITMf v0.9.8 - 'The Dark Side'
|
|_ Net-Creds v1.0 online
2016-07-05 19:42:52 [ProxyPlugins] Adding Replace plugin
|_ Replace v0.2
2016-07-05 19:42:52 [ProxyPlugins] Adding Spoof plugin
|_ Spoof v0.6
2016-07-05 19:42:52 [ARPpoisoner] gatewayip  => 10.26.0.4
2016-07-05 19:42:52 [ARPpoisoner] gatewaymac => 00:00:0c:9f:f1:55
2016-07-05 19:42:52 [ARPpoisoner] targets    => [IPAddress('10.26.184.201')]
2016-07-05 19:42:52 [ARPpoisoner] ignore     => []
2016-07-05 19:42:52 [ARPpoisoner] ip         => 10.26.137.147
2016-07-05 19:42:52 [ARPpoisoner] mac        => 24:77:03:35:bb:e4
2016-07-05 19:42:52 [ARPpoisoner] interface  => wlan0
2016-07-05 19:42:52 [ARPpoisoner] arpmode    => rep
2016-07-05 19:42:52 [ARPpoisoner] interval   => 3
2016-07-05 19:42:52 [Utils] Setting iptables DNS redirection rule from port 53 to 53
2016-07-05 19:42:52 [Utils] Setting ip forwarding to 1
2016-07-05 19:42:52 [Utils] Setting iptables HTTP redirection rule from port 80 to 10000
|  |_ DNS spoofing enabled
|  |_ ARP spoofing enabled
|_ Sergio-Proxy v0.2.1 online
|_ SSLstrip v0.9 by Moxie Marlinspike online
|
|_ MITMf-API online
|_ HTTP server online
|_ DNSChef v0.4 online
|_ SMB server online

2016-07-05 19:42:54 [ARPpoisoner] Resolved 10.26.184.201 => d0:37:42:19:04:61```
``````

**Comment by jc1994jc** [comment] 2016-08-05 03:28
Same problem.

**Comment by lokakit** [comment] 2016-12-05 04:12
Same problem, but iam getting this issue when iam trying to attack external device (phone, another PC) from vm(vm1-kali), when iam attacking vm within same machine its working(vm1-kali ,vm2-windows), any idea what can be cause ?

**Comment by byt3bl33d3r** [comment] 2016-12-13 05:17
Duplicate of #336, closing this issue ticket. Please comment in #336

**Closed by byt3bl33d3r** 2016-12-13 05:17 UTC
